# Route Planner Configuration

# Data paths
data:
  nodes_file: "../data/nodes_bbox_-80.031_40.410_-79.896_40.494.json"
  edges_file: "../data/edges_bbox_-80.031_40.410_-79.896_40.494.json"

# Default coordinates
defaults:
  start: 
    lat: 40.464834
    lon: -79.934860
  end:
    lat: 40.455911
    lon: -79.979289

# Future planner parameters can go here
planner:
  type: "astar"
  # Cost functions to use - can specify one or both
  cost_functions:
    - "distance"  # Plan by distance (km)
    - "time"      # Plan by time (seconds)
  
  # Default speed settings for time-based planning
  default_speed_mph: 25  # Default speed when no max_speed is specified